# Параметры физической задачи
[simulation]
gamma = 1.4
Soda_test = "test3"

# Параметры схемы
[scheme]
methods = ["Godunov"]
solvers = ["Roe"]
N_x = 250
L_x = 1.0

# Граничные условия. free - свободная граница; wall - непроницаемая стена; periodic - периодические
x_right_bound = "free"
x_left_bound = "free"
CFL = 0.25

# Параметры записи
[recording]
fo = 10
step_max = 1000
