# Параметры физической задачи
[simulation]
gamma = 1.4
Soda_test = "test3"

# Параметры схемы
[scheme]
methods = ["MacCORMACK"]
solvers = ["Exact"]

Diffusion = "On"
Q = 0.2

Viscous = "Off"
mu = 1.0

TVD = "Off"
High_order_method = "ENO"
TVD_solver = "Exact"
# Рекомендованы: CHARM, Koren, MC, Osher, ospre, superbee, Sweby 
# vanLeer
TVD_limiter = "vanAlbada1"

N_x = 200
L_x = 1.0

# Граничные условия. free - свободная граница; wall - непроницаемая стена; periodic - периодические
x_right_bound = "free"
x_left_bound = "free"
CFL = 0.125

# Параметры записи
[recording]
fo = 10
step_max = 1000
