[test1]
rho_L = 1.0
u_L = 0.75
P_L = 1.0

rho_R = 0.125
u_R = 0.0
P_R = 0.1

x_gap = 0.3
max_t = 0.2

[test2]
rho_L = 1.0
u_L = -2.0
P_L = 0.4

rho_R = 1.0
u_R = 2.0
P_R = 0.4

x_gap = 0.5
max_t = 0.15

[test3]
rho_L = 1.0
u_L = 0.0
P_L = 1000.0

rho_R = 1.0
u_R = 0.0
P_R = 0.01

x_gap = 0.5
max_t = 0.012

[test4]
rho_L = 5.99924
u_L = 19.5975 
P_L = 460.894 

rho_R = 5.99242 
u_R = -6.19633 
P_R = 46.0950 

x_gap = 0.4
max_t = 0.035

[test5]
rho_L = 1.0 
u_L = -19.59745 
P_L = 1000.0

rho_R = 1.0
u_R = -19.59745
P_R = 0.01

x_gap = 0.8
max_t = 0.012

[test6]
rho_L = 1.0 
u_L = 2.0 
P_L = 0.1

rho_R = 1.0
u_R = -2.0
P_R = 0.1

x_gap = 0.5
max_t = 0.35

[custom]
rho_L = 1.0 
u_L = 2.0 
P_L = 0.1

rho_R = 1.0
u_R = 2.0
P_R = 0.1

x_gap = 0.5
max_t = 0.1
